// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMetNbfUJ5FNdtY0oqQgrm9FIGocaoyaE',
    appId: '1:100768026651:web:1ef678864964de0564a8be',
    messagingSenderId: '100768026651',
    projectId: 'smart-tech-7a97d',
    authDomain: 'smart-tech-7a97d.firebaseapp.com',
    storageBucket: 'smart-tech-7a97d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc1ANCvotKtoa8VATpsWXLuNnuZh0fULk',
    appId: '1:100768026651:android:c1e312c820dc34d464a8be',
    messagingSenderId: '100768026651',
    projectId: 'smart-tech-7a97d',
    storageBucket: 'smart-tech-7a97d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANDgyZ-7DnoVlusCANVVI3JmhIA1CobDI',
    appId: '1:100768026651:ios:a6876fedd995228b64a8be',
    messagingSenderId: '100768026651',
    projectId: 'smart-tech-7a97d',
    storageBucket: 'smart-tech-7a97d.appspot.com',
    iosBundleId: 'com.example.smattech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANDgyZ-7DnoVlusCANVVI3JmhIA1CobDI',
    appId: '1:100768026651:ios:f9665572fa63373d64a8be',
    messagingSenderId: '100768026651',
    projectId: 'smart-tech-7a97d',
    storageBucket: 'smart-tech-7a97d.appspot.com',
    iosBundleId: 'com.example.smattech.RunnerTests',
  );
}
